name: Upload to PyPI

on:
  workflow_dispatch:
    inputs:
      PYPI_API_TOKEN:
        required: true
        description: your API token on PyPI

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          python-version: 3.10
      - name: Build Docker image 
        run: docker build -t flash-attention-wheel . 
      - name: Run Docker container 
        run: docker run -v $(pwd):/app flash-attention-wheel python setup.py sdist bdist_wheel
      - name: Publish package on Pypi using Twine 
        run: | 
          pip install twine 
          # testing purposes 
          twine upload -r testpypi dist/*
          twine upload dist /*
