name: Upload flash attention package to PyPI

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build Docker image that installs dependencies
      run: docker build -t togethercomputer/flash-attention-wheel .
      
    - name: Run Docker container and mount it to the host machine so dist can be accessed by host 
      run: |
        mkdir dist
        docker run -v $(pwd)/dist:/app/dist togethercomputer/flash-attention-wheel:latest
      
    - name: Publish package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_TOKEN }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/*
